import Head from 'next/head';
import { UserInfoArea } from '../../widgets/user-info-area/user-info-area';
import { UserLoginInfoArea } from '../../widgets/user-login-info-area/user-login-info-area';
import { ReviewList } from '../../widgets/review-list/review-list';
import { ProfilePageMenuBar } from '../../widgets/profile-page-menu-bar/profile-page-menu-bar';

import * as S from './profile-page-style';

export const ProfilePage = () => {
  return (
    <>
      <Head>
        <title>Pawland Profile</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <S.ProfilePage>
          <S.UserInfoContainer>
            <UserInfoArea />
            <UserLoginInfoArea />
          </S.UserInfoContainer>
          <S.ListContainer>
            <ProfilePageMenuBar />
            <ReviewList></ReviewList>
          </S.ListContainer>
        </S.ProfilePage>
      </main>
    </>
  );
};
