import { useEffect } from 'react';

import Head from 'next/head';
import { UserInfoArea } from '../../widgets/my-info-area/my-info-area';
import { UserLoginInfoArea } from '../../widgets/user-login-info-area/user-login-info-area';
import { ProfilePageMenuBar } from '../../widgets/profile-page-menu-bar/profile-page-menu-bar';

import * as S from './profile-page-style';
import { MyRegisteredProductList } from '../../widgets/my-registered-product-list/my-registered-product-list';
import { WishList } from '../../widgets/wish-list/wish-list';
import { TransactionHistoryList } from '../../widgets/transaction-history-list/transaction-history-list';
import { MyCommunityList } from '../../widgets/my-community-list/my-community-list';
import { useActiveButtonStore } from '../../shared/store/use-active-button-store/use-active-button-store';
import { useGetUserInfo } from '@entities/user/hooks';
import { useUserStore } from '@entities/user/model';
import { useEffect } from 'react';

interface ActiveButtonState {
  activeButton: string;
}

export const ProfilePage = () => {
  const { data, status } = useGetUserInfo();
  const { setUserInfo } = useUserStore((state) => ({ setUserInfo: state.setUserInfo }));
  const activeButton = useActiveButtonStore((state: ActiveButtonState) => state.activeButton);

  useEffect(() => {
    if (status === 'success' && data) {
      setUserInfo(data);
    }
  }, [data, status]);

  const renderComponent = () => {
    switch (activeButton) {
      case 'register':
        return <MyRegisteredProductList />;
      case 'wish':
        return <WishList itemList={mainListData} />;
      case 'transaction':
        return <TransactionHistoryList />;
      case 'community':
        return <MyCommunityList />;
      default:
        return <MyRegisteredProductList />;
    }
  };

  return (
    <>
      <Head>
        <title>Pawland Profile</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <S.ProfilePage>
          <S.UserInfoContainer>
            <UserInfoArea imageSrc={data?.profileImage} nickname={data?.nickname} description={data?.userDesc} />
            <UserLoginInfoArea />
          </S.UserInfoContainer>
          <S.ListContainer>
            <ProfilePageMenuBar />
            {renderComponent()}
          </S.ListContainer>
        </S.ProfilePage>
      </main>
    </>
  );
};
