import Head from 'next/head';
import Link from 'next/link';

import { SearchInput } from '@shared/ui/inputs';
import { categoryData, CategoryList } from '@widgets/category-list';
import { MainbannerSwiper } from '@widgets/main-banner-swiper';
import { mainBannerData } from '@widgets/main-banner-swiper/lib/main-banner-data';
import { ProductList } from '@widgets/recent-product-list';

import * as S from './home-page-style';

export const HomePage = () => {
  return (
    <>
      <Head>
        <title>Pawland Home</title>
        <meta name='description' content='Generated by create next app' />
        {/* <link rel='icon' href='/favicon.ico' /> */}
      </Head>
      <S.HomePage>
        <S.SwiperArea>
          <MainbannerSwiper mainBannerList={mainBannerData} />
        </S.SwiperArea>
        <S.InputArea>
          <SearchInput placeholder='원하시는 상품을 검색해보세요!' maxWidth='940px' />
        </S.InputArea>
        <S.CategoryArea>
          <CategoryList categoryList={categoryData} />
        </S.CategoryArea>
        <S.ProductListArea>
          <div className='product-title-box'>
            <h3>최신 상품</h3>
            <Link href='/'>더보기</Link>
          </div>
          <ProductList />
        </S.ProductListArea>
      </S.HomePage>
    </>
  );
};
