import { Inter } from 'next/font/google';
import Head from 'next/head';

import { useGetTodoList } from '@entities/todo/hooks';
import { TodoList } from '@entities/todo/ui';
import { AddTodoForm } from '@features/add-todo/ui';

const inter = Inter({ subsets: ['latin'] });

export const Home = () => {
  const { data, status } = useGetTodoList();

  if (status === 'pending') {
    return <div>Loading...</div>;
  }

  if (status === 'error') {
    return <div>Error</div>;
  }

  return (
    <>
      <Head>
        <title>Pawland Home</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={`${inter.className}`}>
        <AddTodoForm />
        <TodoList todoList={data} />
      </main>
    </>
  );
};
