import { useEffect, useState } from 'react';
import { useForm } from 'react-hook-form';

import { Inter } from 'next/font/google';
import Head from 'next/head';

import { addTodoApi, getTodo, Todo } from '@shared/api/todo-api';
import { InputWithLabel } from '@shared/ui/inputs/input-with-label';

const inter = Inter({ subsets: ['latin'] });

export const Home = () => {
  const [todos, setTodos] = useState<Todo[]>([]);

  type TodoInput = {
    todo: string;
  };
  const {
    handleSubmit,
    register,
    reset,
    formState: { errors },
  } = useForm<TodoInput>({
    mode: 'onBlur',
    defaultValues: {
      todo: '',
    },
  });

  const addTodo = async (data: TodoInput) => {
    try {
      const response = await addTodoApi(data.todo);
      setTodos(response);
      reset();
    } catch (error) {
      console.error(error);
    }
  };

  useEffect(() => {
    const getTodos = async () => {
      try {
        const response = await getTodo();
        setTodos(response);
      } catch (error) {
        console.error(error);
      }
    };

    getTodos();
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={`${inter.className}`}>
        <form noValidate onSubmit={handleSubmit(addTodo)}>
          <InputWithLabel
            type='text'
            isError={!!errors.todo}
            id='todo'
            label='Todo title'
            placeholder='please enter todo title'
            {...register('todo', {
              required: {
                value: true,
                message: 'please enter todo title',
              },
            })}
          >
            <span>{errors.todo?.message}</span>
          </InputWithLabel>
          <button type='submit'>Add Todo</button>
        </form>
        <div>
          {todos.map((todo) => (
            <div key={todo.id}>{todo.title}</div>
          ))}
        </div>
      </main>
    </>
  );
};
