import Head from 'next/head';
import { useEffect, useState } from 'react';

import * as S from './edit-page-style';
import { useGetUserInfo } from '@entities/user/hooks';
import { useUserStore } from '@entities/user/model';

export const EditPage = () => {
  const { data, status } = useGetUserInfo();
  const { setUserInfo } = useUserStore((state) => ({ setUserInfo: state.setUserInfo }));
  const [nickname, setNickname] = useState(data?.nickname);
  const [description, setDescription] = useState(data?.userDesc);
  const [selectedFile, setSelectedFile] = useState<string | null>(data?.profileImage || null);
  const [isChanged, setIsChanged] = useState(false);

  const handleFileChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (file) {
      setSelectedFile(URL.createObjectURL(file));
      setIsChanged(true);
    }
  };

  const handleNicknameChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setNickname(e.target.value);
    setIsChanged(true);
  };

  const handleDescriptionChange = (e: React.ChangeEvent<HTMLTextAreaElement>) => {
    setDescription(e.target.value);
    setIsChanged(true);
  };

  useEffect(() => {
    if (status === 'success' && data) {
      setUserInfo(data);
    }
  }, [data, status]);

  const handleSaveProfile = () => {
    setIsChanged(false);
  };

  return (
    <>
      <Head>
        <title>Pawland Profile</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <S.EditPage>
          <S.PageTitle>프로필</S.PageTitle>
          <S.InfoContainer>
            <S.ProfileImage src={selectedFile} alt='프로필 이미지' width={200} height={200} />
            <S.EditButtonArea>
              <S.ImageEditButton htmlFor='fileUpload'>바꾸기</S.ImageEditButton>
              <S.FileUploadInput id='fileUpload' type='file' accept='image/*' onChange={handleFileChange} />

              <S.ImageEditButton>삭제</S.ImageEditButton>
            </S.EditButtonArea>
            <S.InputArea>
              <S.InputItem>
                <S.Label htmlFor='name'>닉네임</S.Label>

                <S.NicknameInput
                  type='text'
                  id='name'
                  name='nickname'
                  value={nickname}
                  onChange={handleNicknameChange}
                />
              </S.InputItem>

              <S.InputItem>
                <S.Label htmlFor='description'>소개</S.Label>
                <S.DescriptionInput
                  id='description'
                  name='description'
                  value={description}
                  onChange={handleDescriptionChange}
                />
              </S.InputItem>
            </S.InputArea>
            <S.LoginInfoArea>
              <S.Label htmlFor='idInfo'>아이디 정보</S.Label>
              <S.LoginInformation> 카카오로 로그인 되었습니다.</S.LoginInformation>
            </S.LoginInfoArea>

            <S.BigButtonArea>
              <S.BigButton>비밀번호 변경하기</S.BigButton>
              <S.SaveButton $isActive={isChanged} onClick={handleSaveProfile}>
                프로필 저장하기
              </S.SaveButton>
              <S.BigButton>로그아웃</S.BigButton>
              <S.UnregisterButton>회원탈퇴</S.UnregisterButton>
            </S.BigButtonArea>
          </S.InfoContainer>
        </S.EditPage>
      </main>
    </>
  );
};
