import Head from 'next/head';

import * as S from './signup-page-style';

export const SignupPage = () => {
  return (
    <>
      <Head>
        <title>Pawland Signup</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <S.SignupPage>Signup page</S.SignupPage>
      </main>
    </>
  );
};
