import Head from 'next/head';

import * as S from './signup-page-style';

export const SignupPage = () => {
  return (
    <>
      <Head>
        <title>Pawland Signup</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <S.SignupPageTitle>회원가입</S.SignupPageTitle>
        <S.SignupPageSpan>회원가입에 필요한 정보를 입력해주세요.</S.SignupPageSpan>
        <S.SignupPageInput placeholder='닉네임을 정해주세요.' />
      </main>
    </>
  );
};
