name: Build Next CI

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  build_next:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['20.12.1']
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run lint:fix
        run: |
          npm run lint:fix || (echo "You should run lint:fix before pr" && exit 1)

      - name: build next
        run: |
          npm run build || (echo "next build failed" && exit 1)
