name: Build Next CI

on:
  workflow_run:
    workflows: [Lint Check and Test CI]
    types: [completed]

jobs:
  build_next:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: build next
        run: |
          npm run build || (echo "next build failed" && exit 1)

  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure'}}
    steps:
      - name: notify failure
        run: echo "The triggering workflow failed"
