name: Lint Check and Test CI
on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  lint_check_and_test:
    runs-on: ubuntu-latest
    env:
      ENV_LOCAL: ${{ secrets.ENV_LOCAL}}

    strategy:
      matrix:
        node-version: ['20.12.1']

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Create dotenv
        run: |
          echo "${{ secrets.ENV_LOCAL }}" > .env.local

      - name: Run lint:fix
        run: |
          npm run lint:fix || (echo "You should run lint:fix before pr" && exit 1)

      - name: typecheck
        run: |
          npm run typecheck || (echo "You should run typecheck before pr" && exit 1)

      - name: test
        env:
          TZ: Asia/Seoul
        run: |
          npm run test:ci || (echo "You should run test before pr" && exit 1)
